---
name: goreleaser
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    name: Run go releaser
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22"

      - name: Fix GOPATH
        run: export PATH=$PATH:$(go env GOPATH)/bin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811 # v5.1.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
